# This is a basic workflow to help you get started with Actions

name: Logic and stuff

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  job1:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, from job1

  job2:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, from Job2

  job3:
      runs-on: ubuntu-latest
      needs: [job2]

      steps:
        - uses: actions/checkout@v3

        - name: Run a one-line script
          run: echo Hello, from Job2
