# This is a basic workflow to help you get started with Actions

name: Scheduled1

# Controls when the workflow will run
on:
  schedule:
    - cron: '*/15 * * * *'

env:
  Variable1: Awesome

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          echo Cron Workflow executed with variable $Variable1
